export const GET_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/GET_LIST_DATA';
export const SET_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/SET_LIST_DATA';
export const START_NEW_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/START_NEW_CHECKUP_DATA';
export const DELETE_ALL_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/DELETE_ALL_CHECKUP_DATA';
export const ADD_EDIT_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/ADD_EDIT_CHECKUP_DATA';
export const SET_MONTHLY_CHECKUP_REPORT_DATA = 'MONTHLY_CHECKUP/SET_REPORT_DATA';
export const GET_PREVIUS_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/GET_PREVIUS_DATA';
export const RESET_PREVIUS_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/RESET_PREVIUS_DATA';
export const SET_PROVISION_REPORT_DATA = 'MONTHLY_CHECKUP/SET_PROVISION_REPORT_DATA';
export const SET_REGULAR_REPORT_DATA = 'MONTHLY_CHECKUP/SET_REGULAR_REPORT_DATA';
export const SET_PREVIOUS_CHECKUP_DATA = 'MONTHLY_CHECKUP/SET_PREVIOUS_CHECKUP_DATA';
export const SET_LAST_START_DATE = 'MONTHLY_CHECKUP/SET_LAST_START_DATE';
export const ROLLOVER_MONTHLY_CHECKUP = 'MONTHLY_CHECKUP/ROLLOVER';
export const DELETE_MONTHLY_CHECKUP_DATA = 'MONTHLY_CHECKUP/DELETE_CHECKUP_DATA';

export const GET_BALANCES_AS_AT = 'MONTHLY_CHECKUP/GET_BALANCES_AS_AT';
export const HISTORICAL_TRACKING_ADD_NUMBERS = 'MONTHLY_CHECKUP/HISTORICAL_TRACKING_ADD_NUMBERS';
export const CHANGE_START_DATE = 'MONTHLY_CHECKUP/CHANGE_START_DATE';

export const GET_MONEY_SMARTS_TRACKING_CARDS = 'MONTHLY_CHECKUP/GET_MONEY_SMARTS_TRACKING_CARDS';
export const UPDATE_MONEY_SMARTS_TRACKING_CARDS =
  'MONTHLY_CHECKUP/UPDATE_MONEY_SMARTS_TRACKING_CARDS';

export const FIND_BANK_CREDIT = 'MONTHLY_CHECKUP/FIND_BANK_CREDIT';
export const SET_START_DATE = 'MONTHLY_CHECKUP/SET_START_DATE';

export const TAKE_MONTHLY_CHECKUP = 'MONTHLY_CHECKUP/TAKE_MONTHLY_CHECKUP';

export const SET_ACTIONS = 'MONTHLY_CHECKUP/SET_ACTIONS';
