export const REFETCH_FINANCIAL_LIST_DATA = 'EXPENSE_DASHBOARD/REFETCH_FINANCIAL_LIST_DATA';
export const GET_FINANCIAL_LIST_DATA = 'EXPENSE_DASHBOARD/GET_FINANCIAL_LIST_DATA';
export const SET_FINANCIAL_LIST_DATA = 'EXPENSE_DASHBOARD/SET_FINANCIAL_LIST_DATA';

export const GET_STATIC_VALUES = 'EXPENSE_DASHBOARD/GET_STATIC_VALUES';
export const SET_FINANCIAL_FILTER_FIELDS = 'EXPENSE_DASHBOARD/SET_FINANCIAL_FILTER_FIELDS';

export const DELETE_FINANCIAL_CARD_ITEM = 'EXPENSE_DASHBOARD/DELETE_FINANCIAL_CARD_ITEM';

export const SET_FETCH_PARAMS = 'EXPENSE_DASHBOARD/SET_FETCH_PARAMS';
export const RESET_FETCHING_FINANCIAL_LIST = 'EXPENSE_DASHBOARD/RESET_FETCHING_FINANCIAL_LIST';

export const GET_GROUPING_AND_ITEMS = 'EXPENSE_DASHBOARD/GET_GROUPING_AND_ITEMS';
export const SET_GROUPING_AND_ITEMS = 'EXPENSE_DASHBOARD/SET_GROUPING_AND_ITEMS';
export const GET_BREAKDOWN_ITEMS = 'EXPENSE_DASHBOARD/GET_BREAKDOWN_ITEMS';

export const SET_IS_LOADING_EXPENSE_DASHBOARD =
  'EXPENSE_DASHBOARD/SET_IS_LOADING_EXPENSE_DASHBOARD';

export const SORT_TYPE = { AMOUNT: 'AMOUNT', KEY: 'KEY' };

export const SET_SELECTED_FILTER_BUTTON = 'EXPENSE_DASHBOARD/SET_SELECTED_FILTER_BUTTON';
