export const ONBOARDING_NEXT_STEP = 'ONBOARDING/NEXT_STEP';
export const ONBOARDING_PREV_STEP = 'ONBOARDING/PREV_STEP';
export const ONBOARDING_LOAD_DATA_LOCAL_STORAGE = 'ONBOARDING/LOAD_DATA_LOCAL_STORAGE';
export const ONBOARDING_UPDATE_DATA = 'ONBOARDING/UPDATE_DATA';
export const ONBOARDING_UPDATE_ASKING_NAME = 'ONBOARDING/UPDATE_ASKING_NAME';
export const ONBOARDING_UPDATE_HOUSEHOLD = 'ONBOARDING/UPDATE_HOUSEHOLD';
export const ONBOARDING_UPDATE_ASSET = 'ONBOARDING/UPDATE_ASSET';
export const ONBOARDING_UPDATE_ASSET_PROPERTY = 'ONBOARDING/UPDATE_ASSET_PROPERTY';
export const ONBOARDING_UPDATE_ASSET_BANK_ACCOUNT = 'ONBOARDING/UPDATE_ASSET_BANK_ACCOUNT';
export const ONBOARDING_UPDATE_ASSET_INVESTMENT = 'ONBOARDING/UPDATE_ASSET_INVESTMENT';
export const ONBOARDING_UPDATE_BORROWING = 'ONBOARDING/UPDATE_BORROWING';
export const ONBOARDING_UPDATE_BORROWING_LIABILITY = 'ONBOARDING/UPDATE_BORROWING_LIABILITY';
export const ONBOARDING_UPDATE_INCOME = 'ONBOARDING/UPDATE_INCOME';
export const ONBOARDING_UPDATE_DATA_INCOME = 'ONBOARDING/UPDATE_DATA_INCOME';

export const ONBOARDING_UPDATE_SPENDING = 'ONBOARDING/UPDATE_SPENDING';
export const ONBOARDING_UPDATE_DATA_SPENDING = 'ONBOARDING/UPDATE_DATA_SPENDING';
export const ONBOARDING_UPDATE_LIST_SPENDING = 'ONBOARDING/UPDATE_LIST_SPENDING';

export const ONBOARDING_SUBMIT = 'ONBOARDING/SUBMIT';
export const ONBOARDING_UPDATE_STEP = 'ONBOARDING/UPDATE_STEP';
export const ONBOARDING_FINISH = 'ONBOARDING/FINISH';
export const ONBOARDING_RESET_DATA = 'ONBOARDING/RESET_DATA';
export const ONBOARDING_SET_EMPTY_INCOME = 'ONBOARDING/ONBOARDING_SET_EMPTY_INCOME';

export const OnboardingStep = {
  GetStarted: 'get_started',
  AskingName: 'asking_name',
  Household: 'household',
  HouseholdKid: 'household_kid',
  HouseholdPartner: 'household_partner',
  Asset: 'asset',
  AssetStoryTelling: 'asset_story_telling',
  BorrowingTelling: 'borrowing_telling',
  IncomeTelling: 'income_telling',
  SpendingTelling: 'spending_telling',
  Success: 'success',
};
