export const GET_MONEY_SMARTS = 'MONEY_SMARTS_DASHBOARD/GET_MONEY_SMARTS';
export const SET_MONEY_SMARTS = 'MONEY_SMARTS_DASHBOARD/SET_MONEY_SMARTS';
export const DELETE_TRANSACTION = 'PROVISION_JAR/DELETE_TRANSACTION';
export const ADD_TRANSACTION = 'PROVISION_JAR/ADD_TRANSACTION';
export const EDIT_TRANSACTION = 'PROVISION_JAR/EDIT_TRANSACTION';
