export const EXPENSE_SUBMIT_DATA = 'EXPENSE/SUBMIT_DATA';
export const EXPENSE_FISNISH = 'EXPENSE/FISNISH';

export const GET_EXPENSE_DETAIL = 'EXPENSE/GET_EXPENSE_DETAIL';
export const SET_EXPENSE_DETAIL = 'EXPENSE/SET_EXPENSE_DETAIL';

export const EXPENSE_SET_RELATED_ASSET = 'EXPENSE/SET_RELATED_ASSET';

export const EXPENSE_GET_GROUP_DATA = 'EXPENSE/GET_GROUP_DATA';
export const EXPENSE_SET_GROUP_DATA = 'EXPENSE/SET_GROUP_DATA';

export const EXPENSE_SUBMIT_GROUP_DATA = 'EXPENSE/SUBMIT_GROUP_DATA';
