export default {
  container: {
    backgroundColor: 'palette.color-dynamic-container',
    padding: 20,
    opacity: 1,
    borderRadius: 10,
  },
  group: {
    marginVertical: 15,
  },
  iconDelete: { position: 'absolute', top: 0, right: 0, padding: 12 },
  buttonAdd: {
    flexDirection: 'row',
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: 'palette.color-line-3',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'palette.color-white-1',
    marginTop: 10,
  },
  buttonAddError: {
    flexDirection: 'row',
    borderRadius: 10,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: 'red',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'palette.color-white-1',
    marginTop: 10,
  },
  buttonAddIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    color: 'palette.color-white-1',
    backgroundColor: 'palette.color-primary-1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardItem: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ECECF4',
    marginBottom: 10,
  },
  incomeType: {
    backgroundColor: '#38C976',
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  textIncomeType: { fontSize: 12, lineHeight: 16, color: '#FFFFFF' },
  textColor: {
    color: 'palette.color-primary-text-1',
  },
  errorInputMessage: {
    color: 'dropdown.message-error-text-color',
    fontSize: 'dropdown.message-error-font-size',
    fontWeight: 'dropdown.message-error-font-weight',
    fontFamily: 'dropdown.message-error-font-family',
    lineHeight: 'dropdown.message-error-line-height',
  },
  trashIcon: { margin: 7 },
  inputIcon: { fontSize: 14, color: 'palette.color-dynamic-line' },
};
