export const GET_ASSET_POSITION = 'ASSET_POSITION/GET_ASSET_POSITION';
export const SET_ASSET_POSITION = 'ASSET_POSITION/SET_ASSET_POSITION';
export const SET_FINANCIAL_CARDS = 'ASSET_POSITION/SET_FINANCIAL_CARDS';
export const SUBMIT_FEEDBACK = 'ASSET_POSITION/SUBMIT_FEEDBACK';
export const SET_CHART_TIME = 'ASSET_POSITION/SET_CHART_TIME';
export const SET_FETCHING = 'ASSET_POSITION/SET_FETCHING';
