export const GET_NOTIFICATION = 'NOTIFICATION/GET_NOTIFICATION';
export const SET_NOTIFICATION = 'NOTIFICATION/SET_NOTIFICATION';
export const SET_IS_FULL_DATA = 'NOTIFICATION/SET_IS_FULL_DATA';
export const SET_TOTAL_BADGE = 'NOTIFICATION/SET_TOTAL_BADGE';
export const SET_MARK_IT_AS_READ = 'NOTIFICATION/SET_MARK_IT_AS_READ';
export const SET_RESET_PAGE_INDEX = 'NOTIFICATION/SET_RESET_PAGE_INDEX';
export const MARK_ALL_READ = 'NOTIFICATION/MARK_ALL_READ';
export const UPDATE_NOTIFICATIONS = 'NOTIFICATION/UPDATE_NOTIFICATIONS';

export const GET_CAMPAIGN = 'NOTIFICATION/GET_CAMPAIGN';
export const TRIGGER_BUTTON_CAMPAIGN = 'NOTIFICATION/CAMPAIGN_TRIGGER_BUTTON';
