export const GET_INDUSTRY_DATA = 'INDUSTRY/GET_DATA';
export const SET_INDUSTRY_SEARCH_DATA = 'INDUSTRY/SET_SEARCH_DATA';
export const GET_INDUSTRY_DIVISION_DATA = 'INDUSTRY/GET_DIVISION_DATA';
export const SET_INDUSTRY_DIVISION_DATA = 'INDUSTRY/SET_DIVISION_DATA';
export const GET_INDUSTRY_CLASS_DATA = 'INDUSTRY/GET_CLASS_DATA';
export const SET_INDUSTRY_CLASS_DATA = 'INDUSTRY/SET_CLASS_DATA';
export const CLEAR_INDUSTRY_SEARCH_DATA = 'INDUSTRY/CLEAR_INDUSTRY_SEARCH_DATA';
