export const CHECK_USER_LOGIN = 'AUTH/CHECK_USER_LOGIN';
export const GET_ACCESS_TOKEN_SUCCESS = 'AUTH/GET_ACCESS_TOKEN_SUCCESS';
export const UPDATE_ACCESS_TOKEN = 'AUTH/UPDATE_ACCESS_TOKEN';
export const UPDATE_PASSWORD_TOKEN = 'AUTH/UPDATE_PASSWORD_TOKEN';
export const UPDATE_REFRESH_TOKEN = 'AUTH/UPDATE_REFRESH_TOKEN';
export const UPDATE_TENANT = 'AUTH/UPDATE_TENANT';

export const USER_LOGIN_REQUEST = 'AUTH/USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL = 'AUTH/USER_LOGIN_FAIL';
export const USER_GET_PROFILE = 'AUTH/USER_GET_PROFILE';
export const USER_SET_PROFILE_DATA = 'AUTH/USER_SET_PROFILE_DATA';
export const USER_UPDATE_TERM_CONDITION = 'AUTH/USER_UPDATE_TERM_CONDITION';
export const ADD_TRUSTED_DEVICE = 'AUTH/ADD_TRUSTED_DEVICE';
export const DELETE_FCM_TOKEN = 'AUTH/DELETE_FCM_TOKEN';
export const USER_CHANGE_PASSWORD = 'AUTH/CHANGE_PASSWORD';
export const USER_UPDATE_USER = 'AUTH/USER_UPDATE_USER';
export const USER_UPDATE_USER_HOUSEHOLD = 'AUTH/USER_UPDATE_USER_HOUSEHOLD';

export const USER_LOGOUT = 'AUTH/USER_LOGOUT';
export const USER_EXPIRE = 'AUTH/USER_EXPIRE';

export const RESET_AUTH = 'AUTH/RESET_AUTH';

export const ON_VERIFY_DEVICE = 'AUTH/ON_VERIFY_DEVICE';
export const ON_REFRESH_DEVICE_ACCESS_TOKEN = 'AUTH/ON_REFRESH_DEVICE_ACCESS_TOKEN';

export const GET_STATIC_VALUES = 'AUTH/GET_STATIC_VALUES';
export const UPDATE_STATIC_VALUES = 'AUTH/UPDATE_STATIC_VALUES';
export const UPDATE_BIOMETRICS_DATA = 'AUTH/UPDATE_BIOMETRICS_DATA';
export const UPDATE_TERM_CONDITION_CONTENT = 'AUTH/UPDATE_TERM_CONDITION_CONTENT';
export const UPDATE_LOGIN_ERROR = 'AUTH/UPDATE_LOGIN_ERROR';

export const ADD_TASK = 'AUTH/ADD_TASK';
export const GET_STATIC_VALUES_DEFAULT = 'AUTH/GET_STATIC_VALUES_DEFAULT';
export const UPDATE_STATIC_VALUES_DEFAULT = 'AUTH/UPDATE_STATIC_VALUES_DEFAULT';

export const GET_CURRENT_TIME = 'AUTH/GET_CURRENT_TIME';
export const SET_CURRENT_TIME = 'AUTH/SET_CURRENT_TIME';

export const SETUP_BIOMETRIC_IN_PROMPT = 'AUTH/SETUP_BIOMETRIC_IN_PROMPT';
export const ON_ACCOUNT_IS_STRONG_AUTH = 'AUTH/ON_ACCOUNT_IS_STRONG_AUTH';
export const UPDATE_BIOMETRICS_MANUAL = 'AUTH/UPDATE_BIOMETRICS_MANUAL';

export const USER_DELETION = 'AUTH/USER_DELETION';

export const UPDATE_USER_EMAIL = 'AUTH/UPDATE_USER_EMAIL';

export const OPEN_MY_KNOWLEDGE = 'AUTH/OPEN_MY_KNOWLEDGE';
