export const GET_DEBT_POSITION = 'DEBT_POSITION/GET_DEBT_POSITION';
export const SET_DEBT_POSITION = 'DEBT_POSITION/SET_DEBT_POSITION';
export const SET_FINANCIAL_CARDS = 'DEBT_POSITION/SET_FINANCIAL_CARDS';
export const SUBMIT_FEEDBACK = 'DEBT_POSITION/SUBMIT_FEEDBACK';
export const SET_CHART_TIME = 'DEBT_POSITION/SET_CHART_TIME';
export const SET_FETCHING = 'DEBT_POSITION/SET_FETCHING';
