export const GET_NET_WORTH = 'NET_WORTH/GET_NET_WORTH';
export const SET_NET_WORTH = 'NET_WORTH/SET_NET_WORTH';
export const SET_FINANCIAL_CARDS = 'NET_WORTH/SET_FINANCIAL_CARDS';
export const SUBMIT_FEEDBACK = 'NET_WORTH/SUBMIT_FEEDBACK';
export const SET_CHART_TIME = 'NET_WORTH/SET_CHART_TIME';
export const SET_FETCHING = 'NET_WORTH/SET_FETCHING';
