export const GET_HISTORICAL_VALUES = 'INSIGHTS_TAB_CONTENT/GET_HISTORICAL_VALUES';
export const SET_HISTORICAL_VALUES = 'INSIGHTS_TAB_CONTENT/SET_HISTORICAL_VALUES';
export const SET_OFFSET_BENEFIT_VALUES = 'INSIGHTS_TAB_CONTENT/SET_OFFSET_BENEFIT_VALUES';
export const SET_FETCHING = 'INSIGHTS_TAB_CONTENT/SET_FETCHING';
export const SET_CHART_TIME = 'INSIGHTS_TAB_CONTENT/SET_CHART_TIME';
