export const GET_WEALTH_SPEED_DATA = 'WEALTH/GET_WEALTH_SPEED_DATA';
export const GET_WEALTH_SPEED_SUCCESS = 'WEALTH/GET_WEALTH_SPEED_SUCCESS';
export const SET_WEALTH_SPEED_DATA = 'WEALTH/SET_WEALTH_SPEED_DATA';
export const GET_HISTORY_WEALTH_SPEED_DATA = 'WEALTH/GET_HISTORY_WEALTH_SPEED_DATA';
export const SET_INDEX = 'WEALTH/SET_INDEX';
