export const VERIFY_AUTHENTICATOR = 'VERIFICATION/VERIFY_AUTHENTICATOR';
export const VERIFY_SUCCESS = 'VERIFICATION/VERIFY_SUCCESS';
export const VERIFY_SMS = 'VERIFICATION/VERIFY_SMS';
export const RESEND_SMS = 'VERIFICATION/RESEND_SMS';
export const GET_TWO_FA_METHODS = 'VERIFICATION/GET_TWO_FA_METHODS';
export const SET_TWO_FA_METHODS = 'VERIFICATION/SET_TWO_FA_METHODS';
export const GENERATE_EMAIL_CODE = 'VERIFICATION/GENERATE_EMAIL_CODE';
export const VERIFY_EMAIL_CODE = 'VERIFICATION/VERIFY_EMAIL_CODE';
