export const SET_LIST_GOALS = 'PERSONAL_GOAL/SET_LIST_GOALS';
export const GET_LIST_GOALS = 'PERSONAL_GOAL/GET_LIST_GOALS';

export const GET_PERSONAL_GOAL = 'PERSONAL_GOAL/GET_PERSONAL_GOAL';
export const SET_PERSONAL_GOAL = 'PERSONAL_GOAL/SET_PERSONAL_GOAL';
export const GET_GOALS_UNTIL_YEAR = 'PERSONAL_GOAL/GET_GOALS_UNTIL_YEAR';

export const GET_UPCOMING_GOAL = 'PERSONAL_GOAL/GET_UPCOMING_GOAL';
export const SET_UPCOMING_GOAL = 'PERSONAL_GOAL/SET_UPCOMING_GOAL';

export const UPLOAD_FILES_START = 'UPLOAD_FILES_START';
export const UPLOAD_FILES_SUCCESS = 'UPLOAD_FILES_SUCCESS';
export const UPLOAD_FILES_FAILURE = 'UPLOAD_FILES_FAILURE';

export const CREATE_PERSONAL_GOAL = 'PERSONAL_GOAL/CREATE';
export const UPDATE_PERSONAL_GOAL = 'PERSONAL_GOAL/UPDATE';

export const SET_LIST_GOALS_YEARS = 'PERSONAL_GOAL/SET_LIST_GOALS_YEARS';
