export const SIGNUP = 'SIGNUP/SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP/SIGNUP_FAIL';
export const SIGNUP_RESET_DATA = 'SIGNUP/SIGNUP_RESET_DATA';
export const FETCH_TERM_CONDITION = 'SIGNUP/FETCH_TERM_CONDITION';
export const UPDATE_SIGNUP_ERROR = 'SIGNUP/UPDATE_SIGNUP_ERROR';
