export const REFETCH_FINANCIAL_LIST_DATA = 'FINANCIAL_DASHBOARD/REFETCH_FINANCIAL_LIST_DATA';
export const GET_FINANCIAL_LIST_DATA = 'FINANCIAL_DASHBOARD/GET_FINANCIAL_LIST_DATA';
export const SET_FINANCIAL_LIST_DATA = 'FINANCIAL_DASHBOARD/SET_FINANCIAL_LIST_DATA';

export const GET_FINANCIAL_SUMMARY_DATA = 'FINANCIAL_DASHBOARD/GET_FINANCIAL_SUMMARY_DATA';
export const SET_FINANCIAL_SUMMARY_DATA = 'FINANCIAL_DASHBOARD/SET_FINANCIAL_SUMMARY_DATA';

export const GET_STATIC_VALUES = 'FINANCIAL_DASHBOARD/GET_STATIC_VALUES';
export const SET_FINANCIAL_FILTER_FIELDS = 'FINANCIAL_DASHBOARD/SET_FINANCIAL_FILTER_FIELDS';

export const DELETE_FINANCIAL_CARD_ITEM = 'FINANCIAL_DASHBOARD/DELETE_FINANCIAL_CARD_ITEM';

export const SET_FETCH_PARAMS = 'FINANCIAL_DASHBOARD/SET_FETCH_PARAMS';
export const RESET_FETCHING_FINANCIAL_LIST = 'FINANCIAL_DASHBOARD/RESET_FETCHING_FINANCIAL_LIST';

export const ARCHIVE_FINANCIAL_CARD_ITEM = 'FINANCIAL_DASHBOARD/ARCHIVE_FINANCIAL_CARD_ITEM';
export const RESTORE_FINANCIAL_CARD_ITEM = 'FINANCIAL_DASHBOARD/RESTORE_FINANCIAL_CARD_ITEM';

export const SET_SELECTED_FILTER_BUTTON = 'FINANCIAL_DASHBOARD/SET_SELECTED_FILTER_BUTTON';
export const SET_FETCH_PARAMS_IS_HANDLED = 'FINANCIAL_DASHBOARD/SET_FETCH_PARAMS_IS_HANDLED';

export const GET_LATEST_AS_AT = 'FINANCIAL_DASHBOARD/GET_LATEST_AS_AT';

export const UPDATE_NEXT_PAY_DATE_START = 'FINANCIAL_DASHBOARD/UPDATE_NEXT_PAY_DATE_START';
