export default {
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  modalContainer: {
    backgroundColor: 'palette.color-dynamic-container',
    padding: 20,
    opacity: 1,
    borderRadius: 10,
  },
  buttonField: {
    width: 150,
  },
  itemAsset: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'palette.color-primary-2',
    borderWidth: 1,
    borderColor: 'palette.color-line-1',
    paddingVertical: 8,
    borderRadius: 30,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  textItemAsset: { textAlign: 'center', color: 'white' },
  locationIcon: {
    color: 'palette.color-primary-text-3',
  },
  borrowingBackground: {
    backgroundColor: 'custom.screens.asset.borrowing-card',
    borderRadius: 6,
  },
  borrowingCardTitle: { padding: 10, fontFamily: 'Poppins-SemiBold' },
  addNewButton: { width: '100%', paddingHorizontal: 15 },
  addNewBorrowingContainer: {
    backgroundColor: 'palette.color-white-1',
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    flexDirection: 'row',
    borderWidth: 1,
    borderRadius: 8,
    borderStyle: 'dashed',
    borderColor: 'palette.vertical-line',
  },
  plusIcon: {
    color: 'palette.color-primary-1',
    padding: 10,
  },
  cardContainer: {
    margin: 0,
    padding: 0,
    backgroundColor: 'palette.color-white-1',
    shadowColor: 'palette.color-white-1',
    borderWidth: 1,
    borderRadius: 10,
    borderTopColor: 'palette.color-line-1',
    borderBottomColor: 'palette.color-line-1',
    borderRightColor: 'palette.color-line-1',
    borderLeftWidth: 4,
    borderLeftColor: 'custom.screens.asset.borrowing-border',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  cartItemContainer: { paddingHorizontal: 15 },
  cartTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  itemTypeContainer: {
    backgroundColor: 'red',
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  itemTypeText: { color: 'white' },
  loansJar: { color: 'custom.screens.asset.borrowing-loans-jar' },
  loansFre: { color: 'palette.color-primary-text-3' },
  currentPaymentText: { color: 'palette.color-primary-text-1' },
  wrapperControl: { position: 'absolute', bottom: 30, left: 20, right: 20 },
};
