export const SET_HOME_DATA = 'HOME/SET_HOME_DATA';
export const GET_HOME_DATA = 'HOME/GET_HOME_DATA';
export const GET_REVIEW = 'HOME/GET_REVIEW';
export const SYNC_FINANCIAL_DATA = 'HOME/SYNC_FINANCIAL_DATA';
export const SET_FEEDBACK_REVIEW = 'HOME/SET_FEEDBACK_REVIEW';
export const SET_DO_FEEDBACK_LATER = 'HOME/SET_DO_FEEDBACK_LATER';
export const SET_ADD_FEEDBACK = 'HOME/SET_ADD_FEEDBACK';
export const SET_SHOW_REVIEW_PROMPT = 'HOME/SET_SHOW_REVIEW_PROMPT';
export const SET_REVIEW_STATUS = 'HOME/SET_REVIEW_STATUS';
export const SET_SHOW_ON_LOGIN = 'HOME/SET_SHOW_ON_LOGIN';
export const GET_SHOW_ON_LOGIN = 'HOME/GET_SHOW_ON_LOGIN';

export const SET_CASH_POSITION = 'HOME/SET_CASH_POSITION';
export const SET_ASSET_POSITION = 'HOME/SET_ASSET_POSITION';
export const SET_NET_WORTH = 'HOME/SET_NET_WORTH';
export const SET_DEBT_POSITION = 'HOME/SET_DEBT_POSITION';

export const SUBMIT_FEEDBACK = 'HOME/SUBMIT_FEEDBACK';
export const SUBMIT_FEEDBACK_SUGGESTION = 'HOME/SUBMIT_FEEDBACK_SUGGESTION';
