export const GET_CASH_POSITION = 'CASH_POSITION/GET_CASH_POSITION';
export const SET_CASH_POSITION = 'CASH_POSITION/SET_CASH_POSITION';
export const SET_FINANCIAL_CARDS = 'CASH_POSITION/SET_FINANCIAL_CARDS';
export const SET_CHART_TIME = 'CASH_POSITION/SET_CHART_TIME';
export const SET_FETCHING = 'CASH_POSITION/SET_FETCHING';
