export const GET_HISTORICAL_LOG_DATA = 'HISTORICAL_LOG/GET_HISTORICAL_LOG';
export const SET_HISTORICAL_LOG_DATA = 'HISTORICAL_LOG/SET_HISTORICAL_LOG';
export const ADD_HISTORICAL_LOG = 'HISTORICAL_LOG/ADD_HISTORICAL_LOG';
export const DELETE_HISTORICAL_LOG = 'HISTORICAL_LOG/DELETE_HISTORICAL_LOG';
