name: "git-setup"
description: "Git setup credential"

inputs:
  gitAuthorEmail:
    description: "Author Email"
    required: false

  gitAuthorName:
    description: "Author Name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        git config --global user.email ${{ inputs.gitAuthorEmail }}
        git config --global user.name ${{ inputs.gitAuthorName }}